doc: add troubleshooting.md docs
signalfx/splunk-otel-ios pull request #122
Opened 2022-12-08 13:07 UTC by Piyush23786

add troubleshooting.md docs

2022-12-08 14:51 UTC, theletterf requested changes

2022-12-09 09:22 UTC, Piyush23786 commented on Troubleshooting.md
> +## Swift Static Libraries
Error during build :- Could not build Objective-C module 'SQLite3'

2022-12-09 09:23 UTC, Piyush23786 commented on Troubleshooting.md
> +3.use_frameworks! :linkage => :static which will generate full frameworks with statically linked libraries and module map files.
For a small application, which does not use multiple pods, the first approach is recommended, but for a bigger project with multiple pods that don't want to be static with or without modular headers, we can use the second case here 
It's based on a business-to-business model.

2022-12-09 09:28 UTC, theletterf commented on Troubleshooting.md
> +## Swift Static Libraries
Thanks. I've updated my suggestion. Please feel free to apply.

2022-12-09 09:29 UTC, theletterf commented
@Piyush23786 Will approve once the suggestions have been applied.

2022-12-09 10:05 UTC, theletterf approved these changes

2022-12-12 16:20 UTC, seemk requested changes
Really shouldn't use copy-pasted sections

2023-05-15 14:38 UTC, closed without merging