MOB-3106: XCFramework Instructions
signalfx/splunk-otel-ios pull request #144
Opened 2023-05-25 20:23 UTC by dvernon-splunk

Adds a markdown file that contains instructions on how to create an XCFramework from the project.

2023-05-26 07:22 UTC, seemk approved these changes
Perhaps we should link to this file from the README as well?

I wonder once we have a new tag/release available, could we mention that we do build and distribute XCFrameworks? At the moment they are built during the CI and placed under artifacts: https://github.com/signalfx/splunk-otel-ios/actions/runs/5084261832

The artifacts will appear under a specific release, although currently it seems only tags are used.

2023-05-26 09:33 UTC, theletterf requested changes
Some docs edits required.

I think we could move this into a `development` folder. WDYT?

2023-05-26 09:33 UTC, theletterf commented on frameworkInstructions.md
> +# How to Build an XCFramework
```suggestion
# How to build an XCFramework
```

2023-05-26 09:33 UTC, theletterf commented on frameworkInstructions.md
> +If you would like to import Splunk Otel as a framework into your project, follow these steps:
```suggestion
If you want to import Splunk Otel as a framework into your project, follow these steps:
```

2023-05-26 09:33 UTC, theletterf commented on frameworkInstructions.md
> +## 1. Ensure the correct build settings.
```suggestion
## 1. Check build settings
```

2023-05-26 09:33 UTC, theletterf commented on frameworkInstructions.md
> +* Build Libraries for Distribution: Yes
```suggestion
Clone the `splunk-otel-ios` repo and open the `SplunkRumWorkspace.xcworkspace` file in Xcode. Navigate to the **Build Settings** tab on the `SplunkOtel` target and make sure the following settings are present:

* Skip Install: No
* Build Libraries for Distribution: Yes
```

2023-05-26 09:33 UTC, theletterf commented on frameworkInstructions.md
> +## 2. Make Archives
```suggestion
## 2. Make archives
```

2023-05-26 09:33 UTC, theletterf commented on frameworkInstructions.md
> +    xcodebuild archive -project SplunkRum.xcodeproj -scheme SplunkOtel -destination "generic/platform=iOS Simulator" -archivePath "archives/SplunkRum-iOS_Simulator"
````suggestion
Open the terminal and navigate to the directory where the `SplunkRum.xcodeproj` file is located, for example `SplunkRumWorkspace/SplunkRum`. 

Run the following command to create a new archives directory with the file `SplunkRum-iOS.xcarchive` inside:

```bash
    xcodebuild archive -project SplunkRum.xcodeproj -scheme SplunkOtel -destination "generic/platform=iOS" -archivePath "archives/SplunkRum-iOS"
```

Repeat the process for the simulator platform:

```bash
    xcodebuild archive -project SplunkRum.xcodeproj -scheme SplunkOtel -destination "generic/platform=iOS Simulator" -archivePath "archives/SplunkRum-iOS_Simulator"
```
````

2023-05-26 09:33 UTC, theletterf commented on frameworkInstructions.md
> +Paste the following code into the terminal:
```suggestion
Run the following command to create a new archives directory with the file `SplunkRum-iOS.xcarchive`:
```

2023-05-26 09:33 UTC, theletterf commented on frameworkInstructions.md
> +This will create a new xcframeworks directory with the SplunkOtel.xcframework file inside of it.
````suggestion
```bash
    xcodebuild -create-xcframework -archive archives/SplunkRum-iOS.xcarchive -framework SplunkOtel.framework -archive archives/SplunkRum-iOS_Simulator.xcarchive -framework SplunkOtel.framework -output xcframeworks/SplunkOtel.xcframework
```
````

2023-05-26 09:33 UTC, theletterf commented on frameworkInstructions.md
> +Open your project in XCode and drag and drop the SplunkOtel.xcframework into the project navigator. This should automatically import the framework.
```suggestion
## 4. Import the XCFramework into your project

Open your project in Xcode and drag the `SplunkOtel.xcframework` file into the project navigator. This automatically imports the framework. 
```

2023-05-26 09:34 UTC, theletterf commented
@seemk These instructions are for instrumentation developers or for users? If they're for users, they should be in the user docs. Would a user build an XCFramework? Why?

2023-05-26 09:43 UTC, seemk commented
> @seemk These instructions are for instrumentation developers or for users? If they're for users, they should be in the user docs. Would a user build an XCFramework? Why?

For advanced users, we've had requests for how to build the distro as an xcframework, but these are pretty rare cases

2023-05-26 10:14 UTC, theletterf commented
@seemk If this is for customers, even if advanced, it should go into the official docs. I suggest we close this PR. I'll open a docs one in https://github.com/splunk/public-o11y-docs and link to this.

2023-05-30 16:05 UTC, theletterf commented
Closing after checking with @dvernon-splunk — will move to the docs repo.

2023-05-30 16:05 UTC, closed without merging

2023-06-07 22:03 UTC, jnino-splunk commented
@theletterf where could I find where this lives now? Is it user accessible?

2023-06-08 09:04 UTC, theletterf commented
@jnino-splunk It's in the docs PR we're building for GA: https://github.com/splunk/private-o11y-docs/pull/882/files

2023-06-08 13:17 UTC, jnino-splunk commented
@theletterf  ah okay so not https://github.com/splunk/public-o11y-docs. I will have to wait for access to the private docs repo.